name: CI workflow


on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: Set up java
        uses: actions/setup-java@v1.4.4
        with:
          java-version: 11

      - name: Set up AWS SAM
        uses: aws-actions/setup-sam@v1

      - name: Set up AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: SAM Build
        run: sam build --template ./template.yaml --build-dir ./.aws-sam/build

      - name: SAM Package
        run: sam package --template-file ./.aws-sam/build/template.yaml --output-template-file ./.aws-sam/build/packaged-template.yaml --s3-bucket bank-statement-app-bucket

      - name: SAM Deploy
        run: sam deploy --template-file ./.aws-sam/build/packaged-template.yaml --stack-name bank-statements-stack --s3-bucket bank-statement-app-bucket --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM
